"""Guard the detect-only report line format in SKILL.md against template drift.

WU4's report parser depends on the "Confirmed but not fixed" section emitting a
structured, ``·``-separated line. If the template ever loses that structure this
test fails in CI before the parser silently mis-reads a future report.

bugsweep-mu3: the "Findings (machine-readable)" block is no longer model-authored.
scripts/finalize.sh (via scripts/summarize.sh) now generates that section from the
deterministic <RUN_DIR>/run-summary.json reduction and appends it to report.md itself
(see bench/scorer/run_summary.py and tests/bats/summarize.bats) — so prose and JSON
never diverge, which a model-authored block (format varied run-to-run) could not
guarantee. SKILL.md must therefore instruct the model NOT to author that section,
rather than embed a model-facing JSON example for it to imitate.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SKILL_MD = REPO_ROOT / "SKILL.md"
SECTION_HEADER = "## Confirmed but not fixed (detect-only or below severity floor)"
JSON_BLOCK_SECTION = "## Findings (machine-readable)"

# Tokens the structured line MUST contain (bare angle-bracket placeholders in the
# template). file:line is checked as the joined token to pin the colon form.
REQUIRED_TOKENS = ["<BUG-ID>", "<severity>", "<category>", "<file>:<line>"]


def _section_window(text: str, header: str) -> str:
    """Return the lines under ``header`` up to the next ``## `` header or EOF.

    Scoping the assertion to this window keeps the test honest if sections are
    reordered or another section happens to share token names (e.g. the "Fixed"
    line at SKILL.md:191 uses a similar but distinct format).
    """
    lines = text.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if line.strip() == header)
    except StopIteration as exc:  # pragma: no cover - failure path asserted below
        raise AssertionError(f"SKILL.md is missing the section header: {header!r}") from exc
    window: list[str] = []
    for line in lines[start + 1 :]:
        if line.startswith("## "):
            break
        window.append(line)
    return "\n".join(window)


def test_skill_md_exists() -> None:
    assert SKILL_MD.is_file(), f"expected SKILL.md at {SKILL_MD}"


def test_detect_only_section_uses_structured_line() -> None:
    text = SKILL_MD.read_text(encoding="utf-8")
    window = _section_window(text, SECTION_HEADER)

    structured = [
        line
        for line in window.splitlines()
        if "·" in line and all(token in line for token in REQUIRED_TOKENS)
    ]
    assert structured, (
        "expected a structured '·'-separated line under "
        f"{SECTION_HEADER!r} containing {REQUIRED_TOKENS}; section window was:\n{window}"
    )


def test_detect_only_section_has_no_unstructured_placeholder() -> None:
    """The old free-form placeholder must be gone so the parser has one shape."""
    window = _section_window(SKILL_MD.read_text(encoding="utf-8"), SECTION_HEADER)
    assert "<one line per item>" not in window


def test_skill_md_forbids_model_authored_machine_readable_section() -> None:
    """SKILL.md must tell the model NOT to author the machine-readable block.

    scripts/finalize.sh (via scripts/summarize.sh) generates and appends
    ``## Findings (machine-readable)`` itself from run-summary.json, so the
    template must instruct the model to leave it alone rather than embed an
    example JSON array for the model to imitate (that was the source of the
    run-to-run format drift bugsweep-mu3 fixes).
    """
    text = SKILL_MD.read_text(encoding="utf-8")
    section_name = JSON_BLOCK_SECTION.removeprefix("## ")
    assert section_name in text, (
        f"SKILL.md should still reference the section name {section_name!r} "
        "(to tell the model it's generated, not to author it)"
    )
    assert "Do **not** author" in text or "do not author" in text.lower(), (
        "SKILL.md must explicitly instruct the model not to author the "
        f"{JSON_BLOCK_SECTION!r} section itself"
    )


def test_skill_md_no_longer_embeds_a_model_facing_json_example() -> None:
    """The old model-facing JSON array example must be gone (script-generated now)."""
    text = SKILL_MD.read_text(encoding="utf-8")
    assert '"bug_id": "BUG-1"' not in text, (
        "SKILL.md still embeds the old model-facing JSON example; the "
        "machine-readable block is now script-generated by finalize.sh/"
        "summarize.sh from run-summary.json, so the model should not be shown "
        "an example to imitate"
    )
